# Black Rhino source catalogue transcribed from the provided stock-taking pages.
# Selling prices are KES. Stock quantities were not present, so seed stock is 0.
# Size normalization: 1/2 and HALF = 500ml; 1/4 = 250ml.
CATALOG = [
    # Beer / cider / RTD
    ("Guinness", "Guinness", "", "270", "Beer"),
    ("Tusker", "Tuskers", "", "230", "Beer"),
    ("White Cap", "Whitecap", "", "250", "Beer"),
    ("Balozi", "Balozi", "", "230", "Beer"),
    ("Pilsner", "Pilsner", "", "230", "Beer"),
    ("Summit", "Summit", "", "230", "Beer"),
    ("Tusker Light", "Tusker Light", "", "230", "Beer"),
    ("Tusker Malt", "Tusker Malt", "", "250", "Beer"),
    ("Black Ice", "Black Ice", "", "250", "Beer"),
    ("Snapp", "Snapp", "", "250", "Beer"),
    ("Punch", "Punch", "", "250", "Beer"),
    ("Ice Berry", "Ice Berry", "", "250", "Beer"),
    ("Tusker Cinder", "Tusker Cinder", "", "250", "Beer"),
    ("Guinness Smooth", "Guinness Smooth", "", "300", "Beer"),
    ("Henken", "Henken", "", "250", "Beer"),
    ("Hunter Dry", "Hunter Dry", "", "350", "Cider"),
    ("Guinness", "Guinness Can", "", "300", "Beer"),
    ("Tusker", "Tusker Can", "", "300", "Beer"),
    ("White Cap", "Whitecap Can", "", "300", "Beer"),
    ("Balozi", "Balozi Can", "", "300", "Beer"),
    ("Pilsner", "Pilsner Can", "", "300", "Beer"),
    ("Tusker Light", "Tusker Light Can", "", "300", "Beer"),
    ("Tusker Malt", "Tusker Malt Can", "", "300", "Beer"),
    ("Black Ice", "Black Ice Can", "", "250", "Beer"),
    ("Snapp", "Snapp Can", "", "250", "Beer"),
    ("Punch", "Punch Can", "", "250", "Beer"),
    ("Ice Berry", "Ice Berry Can", "", "250", "Beer"),
    ("Tusker Cinder", "Tusker Cinder Can", "", "300", "Beer"),
    ("Guinness Smooth", "Smooth Can", "", "250", "Beer"),
    ("Heineken", "Heineken Can", "", "400", "Beer"),
    ("Guarana", "Guarana Can", "", "250", "Soft Drinks"),
    ("Goddons", "Goddons Can", "", "300", "Beer"),
    ("Goddons", "Goddons Can Pink", "", "300", "Beer"),
    ("Gin N Tonic Pink N Purple", "Gin N Tonic Pink N Purple", "", "300", "Ready to Drink"),
    ("Fax", "Fax Can", "", "300", "Beer"),
    ("Manyatta", "Manyatta Can", "", "350", "Beer"),
    ("Manyatta", "Manyatta Bottle", "", "300", "Beer"),
    # Wine / sparkling
    ("Casaa Bwena", "Casaa Bwena", "", "1200", "Wine"),
    ("Caprice", "Caprice", "", "1200", "Wine"),
    ("Caprice", "Caprice Bottle", "", "1500", "Wine"),
    ("Four Cousin", "Four Cousin 750ml", "750ml", "1500", "Wine"),
    # Soft / energy / water
    ("Red Bull", "Redbull", "", "250", "Energy Drinks"),
    ("Monster", "Monster", "", "300", "Energy Drinks"),
    ("Predator", "Predator", "", "100", "Energy Drinks"),
    ("Lemonade", "Lemonade", "", "100", "Soft Drinks"),
    ("Soda", "Soda", "", "100", "Soft Drinks"),
    ("Water", "Water", "1L", "100", "Water"),
    ("Jack Daniel's", "Jack Daniels 1 Liter", "1L", "6000", "Whisky"),
    ("Jack Daniel's", "Jack Daniels 750ml", "750ml", "5000", "Whisky"),
    # Whisky
    ("Johnnie Walker Black Label", "Black Labels 1 Liter", "1L", "5500", "Whisky"),
    ("Johnnie Walker Black Label", "Black Label 750ml", "750ml", "4500", "Whisky"),
    ("Johnnie Walker Black Label", "Black Label Half", "500ml", "2500", "Whisky"),
    ("Johnnie Walker Black Label", "Black Label 1/4", "250ml", "1500", "Whisky"),
    ("Johnnie Walker Double Black", "Double Black 1ltr", "1L", "", "Whisky"),
    ("Johnnie Walker Double Black", "Double Black 750ml", "750ml", "", "Whisky"),
    ("Jameson", "Jameson 1 Liter", "1L", "5000", "Whisky"),
    ("Jameson", "Jameson 750ml", "750ml", "4500", "Whisky"),
    ("Jameson", "Jameson Half", "500ml", "2600", "Whisky"),
    ("Singleton", "Singleton", "", "8000", "Whisky"),
    ("Jimmy Jimro", "Jimmy Jimro", "", "500", "Whisky"),
    ("Hennessy", "Hennessy", "", "8500", "Brandy"),
    ("Jagermeister", "Jagamiser", "", "5500", "Liqueurs"),
    ("Grants", "Grants 1 Liter", "1L", "3500", "Whisky"),
    ("Grants", "Grants 750", "750ml", "3000", "Whisky"),
    ("Grants", "Grants 1/2", "500ml", "2200", "Whisky"),
    # Vodka
    ("Smirnoff Vodka", "Smirnoff Vodka 750", "750ml", "2000", "Vodka"),
    ("Smirnoff Vodka", "Smirnoff 1/2", "500ml", "900", "Vodka"),
    ("Smirnoff Vodka", "Smirnoff 1/4", "250ml", "650", "Vodka"),
    # Gin
    ("Gordon's", "Gordons 750", "750ml", "2000", "Gin"),
    ("Gilbey's", "Gilbass 750", "750ml", "2000", "Gin"),
    ("Gilbey's", "Gilbass 1/2", "500ml", "900", "Gin"),
    ("Gilbey's", "Gilbass 1/4", "250ml", "650", "Gin"),
    # Rum
    ("Captain Morgan", "Captain Morgan 750ml", "750ml", "1500", "Rum"),
    ("Captain Morgan", "Captain Morgan 250ml", "250ml", "500", "Rum"),
    # Brandy / spirits
    ("Viceroy", "Viceroy 750", "750ml", "2000", "Brandy"),
    ("Viceroy", "Viceroy 1/2", "500ml", "900", "Brandy"),
    ("Viceroy", "Viceroy 1/4", "250ml", "650", "Brandy"),
    ("Hunters", "Hunters 750ml", "750ml", "1700", "Cider"),
    ("Hunters", "Hunters 1/2", "500ml", "700", "Cider"),
    ("Hunters", "Hunters 1/4", "250ml", "400", "Cider"),
    ("County", "County 750ml", "750ml", "1100", "Brandy"),
    ("County", "County 1/4", "250ml", "350", "Brandy"),
    ("Kenya Cane", "Kenya Cane 750ml", "750ml", "1100", "Brandy"),
    ("Kenya Cane", "Kenya Cane 1/2", "500ml", "600", "Brandy"),
    ("Kenya Cane", "Kenya Cane 1/4", "250ml", "350", "Brandy"),
    ("Bold 7", "Bold 7 750ml", "750ml", "2000", "Brandy"),
    ("Bold 7", "Bold 7 1/2", "500ml", "900", "Brandy"),
    ("Bold 7", "Bold 7 1/4", "250ml", "650", "Brandy"),
    ("Richot", "Richot 750ml", "750ml", "2000", "Brandy"),
    ("Richot", "Richot 1/2", "500ml", "900", "Brandy"),
    ("Richot", "Richot 1/4", "250ml", "650", "Brandy"),
    ("Vats 69", "Vats 69 750ml", "750ml", "2400", "Brandy"),
    ("Vats 69", "Vats 1/2", "500ml", "1200", "Brandy"),
    ("Black N' White", "Black N' White 750ml", "750ml", "1500", "Whisky"),
    ("Black N' White", "Black N' White 1/2", "500ml", "800", "Whisky"),
    ("Crome", "Crome 750ml", "750ml", "1000", "Brandy"),
    ("Crome", "Crome 1/4", "250ml", "350", "Brandy"),
    ("Konyagi", "Konyagi 750ml", "750ml", "1200", "Gin"),
    ("Konyagi", "Konyagi 1/2", "500ml", "800", "Gin"),
    ("Konyagi", "Konyagi 1/4", "250ml", "450", "Gin"),
    ("V.N.A", "V N A 750ml", "750ml", "1400", "Brandy"),
    ("V.N.A", "V N A 1/4 500", "250ml", "500", "Brandy"),
    ("Best", "Best 750ml", "750ml", "1700", "Brandy"),
    ("Best Cream", "Best Cream", "", "1600", "Liqueurs"),
    ("Best", "Best 1/2", "500ml", "800", "Brandy"),
    ("John Bar", "Johnbar 1Liter", "1L", "3000", "Brandy"),
    ("John Bar", "Jonbar 750", "750ml", "2500", "Brandy"),
    # Other alcoholic / wine / RTD
    ("Savannah", "Savannah", "", "350", "Cider"),
    ("Del Monte", "Del Monte", "", "350", "Other"),
    ("Danhill", "Danhill", "", "30", "Other"),
    ("Sportman", "Sportman", "", "25", "Other"),
    ("SM", "SM", "", "20", "Other"),
    ("Best", "Best 1/4", "250ml", "450", "Brandy"),
    ("Black Label Tots", "Black Label Tots", "", "250", "Whisky"),
    ("Panadol", "Panadol", "", "20", "Other"),
    ("Mara Moja", "Mara Moja", "", "20", "Other"),
    ("Red Label", "Red Label 750ml", "750ml", "2500", "Whisky"),
    ("Red Label", "Red Label 350ml", "350ml", "1500", "Whisky"),
    ("Dresso Mobile", "Dresso Mobile", "", "2300", "Other"),
    ("4th Street", "4th Street", "", "1500", "Wine"),
    ("Amarula", "Amarula", "", "3500", "Liqueurs"),
    ("K.O", "K.O", "", "200", "Other"),
]
